// <auto-generated />
namespace EntityFRa.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Secondary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Secondary));
        
        string IMigrationMetadata.Id
        {
            get { return "202205141856006_Secondary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
